name: CI/CD Pipeline for Image Service
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  JAVA_VERSION: '25'

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
          server-id: 'github'
          server-password: GH_PACKAGES_TOKEN

      - name: Build
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean package -Dskip.surefire.tests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact-jar
          path: target/*.jar
          retention-days: 2

      - name: Upload target build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/
          retention-days: 2

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/

      - name: Run Unit tests
        run: mvn test

      - name: Upload unit-test surefire reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-test-reports
          path: target/surefire-reports/
          retention-days: 2

      - name: Upload unit tests coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-coverage-unit-report
          path: target/jacoco-unit.exec
          retention-days: 2

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/

      - name: Run IT tests
        run: >
          mvn verify
          -Dskip.surefire.tests
          -Dspring-boot.repackage.skip=true

      - name: Upload IT failsafe reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: it-test-reports
          path: target/failsafe-reports/
          retention-days: 2

      - name: Upload it tests coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-coverage-it-report
          path: target/jacoco-it.exec
          retention-days: 2

  code-analysis:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    needs: [ unit-tests, integration-tests ]
    env:
      SONAR_PROJECT_KEY: cannibal-kektor_gallery-image-service
    permissions:
      security-events: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/

      - name: Download surefire test reports
        uses: actions/download-artifact@v4
        with:
          name: surefire-test-reports
          path: target/surefire-reports

      - name: Download failsafe test reports
        uses: actions/download-artifact@v4
        with:
          name: it-test-reports
          path: target/failsafe-reports

      - name: Download unit coverage exec
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage-unit-report
          path: target/

      - name: Download IT coverage exec
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage-it-report
          path: target/

      - name: Merge JaCoCo reports
        run: |
          mvn jacoco:merge@merge-unit-and-integration-reports
          mvn jacoco:report@merged-report

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-merged/jacoco.xml
          -Dsonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports

      - name: SonarCloud Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        with:
          pollingTimeoutSec: 600
          scanMetadataReportFile: target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: code-analysis
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    env:
      IMAGE_NAME: gallery-image-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact-jar
          path: target/

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=commit-
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          build-contexts: |
            maven-conf=./conf/mvn
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: /tmp/docker-image.tar
          retention-days: 1